#!/usr/bin/python2

# Program : zeds.py
#    MOTD : I like trains ! :)

# I'M NOT RESPONSIBLE FOR YOURS ACTS

# R0 -> Startup Items 
# L0 -> Agents
# L1 -> Daemons
# H0 -> Hosts
# S0 -> Safari conf
# S1 -> Safari Plugins
# S2 -> Safari Extensions

import os         # Process info
import getpass    #    User info
import platform   #      OS info
import biplist    #    Conf info
import subprocess #  Update info

from time import gmtime, strftime

_sAuthor         = "MrHawy"
_sCurrentOS      = platform.system() + ' ' + platform.release() 
_sCurrentTime    = strftime("%Y-%m-%d %H:%M:%S", gmtime())
_sCurrentVersion = "0.3"
_sCurrentYear    = "2014"
_sCurrentUser    = getpass.getuser()

_lSafeHosts = ['#','127.0.0.1localhost','255.255.255.255broadcasthost','::1localhost','fe80::1%lo0localhost']

_lSafeSystemAgents = ['com.apple.accountsd.plist',
'com.apple.AddressBook.abd.plist',
'com.apple.AddressBook.AssistantService.plist',
'com.apple.AddressBook.SourceSync.plist',
'com.apple.AirPlayUIAgent.plist',
'com.apple.AirPortBaseStationAgent.plist',
'com.apple.alf.useragent.plist',
'com.apple.aos.migrate.plist',
'com.apple.AOSPushRelay.plist',
'com.apple.AppleGraphicsWarning.plist',
'com.apple.appleseed.seedusaged.plist',
'com.apple.appsleepd.plist',
'com.apple.appstoreupdateagent.plist',
'com.apple.apsctl.plist',
'com.apple.assistant_service.plist',
'com.apple.assistantd.plist',
'com.apple.AssistiveControl.plist',
'com.apple.avrcpagent.plist',
'com.apple.BezelUI.plist',
'com.apple.bluetoothUIServer.plist',
'com.apple.bookstoreagent.plist',
'com.apple.btsa.plist',
'com.apple.CalendarAgent.plist',
'com.apple.CalendarAgentLauncher.plist',
'com.apple.cfnetwork.AuthBrokerAgent.plist',
'com.apple.cfnetwork.cfnetworkagent.plist',
'com.apple.cfprefsd.xpc.agent.plist',
'com.apple.cmfsyncagent.plist',
'com.apple.ContainerRepairAgent.plist',
'com.apple.cookied.plist',
'com.apple.coredata.externalrecordswriter.plist',
'com.apple.CoreLocationAgent.plist',
'com.apple.CoreRAIDAgent.plist',
'com.apple.coreservices.appleid.authentication.plist',
'com.apple.coreservices.uiagent.plist',
'com.apple.csuseragent.plist',
'com.apple.cvmsCompAgent_i386.plist',
'com.apple.cvmsCompAgent_i386_1.plist',
'com.apple.cvmsCompAgent_x86_64.plist',
'com.apple.cvmsCompAgent_x86_64_1.plist',
'com.apple.cvmsCompAgentLegacy_i386.plist',
'com.apple.cvmsCompAgentLegacy_i386_1.plist',
'com.apple.cvmsCompAgentLegacy_x86_64.plist',
'com.apple.cvmsCompAgentLegacy_x86_64_1.plist',
'com.apple.DiagnosticReportCleanUpAgent.plist',
'com.apple.DiskArbitrationAgent.plist',
'com.apple.distnoted.xpc.agent.plist',
'com.apple.Dock.plist',
'com.apple.dt.CommandLineTools.installondemand.plist',
'com.apple.EscrowSecurityAlert.plist',
'com.apple.familycontrols.useragent.plist',
'com.apple.FileStatsAgent.plist',
'com.apple.FileSyncAgent.PHD.plist',
'com.apple.FilesystemUI.plist',
'com.apple.Finder.plist',
'com.apple.findmymacmessenger.plist',
'com.apple.fontd.useragent.plist',
'com.apple.FontRegistryUIAgent.plist',
'com.apple.FontValidator.plist',
'com.apple.FontValidatorConduit.plist',
'com.apple.FontWorker.plist',
'com.apple.FTCleanup.plist',
'com.apple.gamed.plist',
'com.apple.helpd.plist',
'com.apple.icbaccountsd.plist',
'com.apple.icloud.AOSNotificationAgent.plist',
'com.apple.icloud.AOSNotificationLoginAgent.plist',
'com.apple.identityservicesd.plist',
'com.apple.imagent.plist',
'com.apple.imklaunchagent.plist',
'com.apple.IMLoggingAgent.plist',
'com.apple.installd.user.plist',
'com.apple.isst.plist',
'com.apple.java.InstallOnDemand.plist',
'com.apple.java.updateSharing.plist',
'com.apple.KerberosHelper.LKDCHelper.plist',
'com.apple.lateragent.plist',
'com.apple.LaunchServices.lsboxd.plist',
'com.apple.librariand.plist',
'com.apple.locationmenu.plist',
'com.apple.lookupd.plist',
'com.apple.ManagedClient.agent.plist',
'com.apple.Maps.pushdaemon.plist',
'com.apple.maspushagent.plist',
'com.apple.mbloginhelper.user.plist',
'com.apple.mbpluginhost.user.plist',
'com.apple.mdmclient.agent.plist',
'com.apple.mdmclient.cloudconfig.agent.plist',
'com.apple.mdworker.32bit.plist',
'com.apple.mdworker.bundles.plist',
'com.apple.mdworker.isolation.plist',
'com.apple.mdworker.lsb.plist',
'com.apple.mdworker.mail.plist',
'com.apple.mdworker.shared.plist',
'com.apple.mdworker.single.plist',
'com.apple.mdworker.sizing.plist',
'com.apple.metadata.mdflagwriter.plist',
'com.apple.metadata.mdwrite.plist',
'com.apple.midiserver.plist',
'com.apple.netauth.user.auth.plist',
'com.apple.netauth.user.gui.plist',
'com.apple.NetworkDiagnostics.plist',
'com.apple.noticeboard.agent.plist',
'com.apple.notificationcenterui.plist',
'com.apple.nsnetworkd.plist',
'com.apple.PackageKit.InstallStatus.plist',
'com.apple.parentalcontrols.check.plist',
'com.apple.pboard.plist',
'com.apple.pbs.plist',
'com.apple.PCIESlotCheck.plist',
'com.apple.pictd.plist',
'com.apple.pluginkit.pkd.plist',
'com.apple.printtool.agent.plist',
'com.apple.printuitool.agent.plist',
'com.apple.PubSub.Agent.plist',
'com.apple.quicklook.32bit.plist',
'com.apple.quicklook.config.plist',
'com.apple.quicklook.plist',
'com.apple.quicklook.ui.helper.plist',
'com.apple.rcd.plist',
'com.apple.recentsd.plist',
'com.apple.ReclaimSpaceAgent.plist',
'com.apple.RemoteDesktop.plist',
'com.apple.ReportCrash.plist',
'com.apple.ReportCrash.Self.plist',
'com.apple.ReportGPURestart.plist',
'com.apple.ReportPanic.plist',
'com.apple.safaridavclient.plist',
'com.apple.SafariNotificationAgent.plist',
'com.apple.sbd.plist',
'com.apple.scopedbookmarkagent.xpc.plist',
'com.apple.ScreenReaderUIServer.plist',
'com.apple.screensharing.agent.plist',
'com.apple.screensharing.MessagesAgent.plist',
'com.apple.scrod.plist',
'com.apple.secd.plist',
'com.apple.security.agentStub.plist',
'com.apple.security.cloudkeychainproxy.plist',
'com.apple.security.DiskUnmountWatcher.plist',
'com.apple.security.keychain-circle-notification.plist',
'com.apple.ServiceManagement.LoginItems.plist',
'com.apple.sharingd.plist',
'com.apple.soagent.plist',
'com.apple.SocialPushAgent.plist',
'com.apple.softwareupdate_notify_agent.plist',
'com.apple.speech.feedbackservicesserver.plist',
'com.apple.speech.recognitionserver.plist',
'com.apple.speech.speechdatainstallerd.plist',
'com.apple.speech.speechsynthesisd.plist',
'com.apple.speech.synthesisserver.plist',
'com.apple.spindump_agent.plist',
'com.apple.store_helper.plist',
'com.apple.storeagent.plist',
'com.apple.SubmitDiagInfo.plist',
'com.apple.syncdefaultsd.plist',
'com.apple.syncservices.SyncServer.plist',
'com.apple.syncservices.uihandler.plist',
'com.apple.systemprofiler.plist',
'com.apple.SystemUIServer.plist',
'com.apple.talagent.plist',
'com.apple.tccd.plist',
'com.apple.tiswitcher.plist',
'com.apple.TMHelperAgent.plist',
'com.apple.TMHelperAgent.SetupOffer.plist',
'com.apple.TrustEvaluationAgent.plist',
'com.apple.ubd.plist',
'com.apple.universalaccessAuthWarn.plist',
'com.apple.universalaccesscontrol.plist',
'com.apple.universalaccessd.plist',
'com.apple.unmountassistant.useragent.plist',
'com.apple.USBAgent.plist',
'com.apple.UserEventAgent-Aqua.plist',
'com.apple.UserEventAgent-LoginWindow.plist',
'com.apple.usernoted.plist',
'com.apple.UserNotificationCenterAgent-LoginWindow.plist',
'com.apple.UserNotificationCenterAgent.plist',
'com.apple.VoiceOver.plist',
'com.apple.warmd_agent.plist',
'com.apple.WebKit.PluginAgent.plist',
'com.apple.wifi.WiFiKeychainProxy.plist',
'com.apple.xmigrationhelper.user.plist',
'com.apple.ZoomWindow.plist']

_lSafeSystemDaemons = ['com.apple.afpfs_afpLoad.plist',
'com.apple.afpfs_checkafp.plist',
'com.apple.AirPlayXPCHelper.plist',
'com.apple.airport.wps.plist',
'com.apple.airportd.plist',
'com.apple.airportPrefsUpdater.plist',
'com.apple.alf.agent.plist',
'com.apple.AOSNotificationOSX.plist',
'com.apple.AppleFileServer.plist',
'com.apple.appleseed.fbahelperd.plist',
'com.apple.applessdstatistics.plist',
'com.apple.apsd.plist',
'com.apple.aslmanager.plist',
'com.apple.atrun.plist',
'com.apple.audio.coreaudiod.plist',
'com.apple.auditd.plist',
'com.apple.autofsd.plist',
'com.apple.automountd.plist',
'com.apple.awacsd.plist',
'com.apple.backupd-auto.plist',
'com.apple.backupd.plist',
'com.apple.blued.plist',
'com.apple.bluetoothaudiod.plist',
'com.apple.bnepd.plist',
'com.apple.bsd.dirhelper.plist',
'com.apple.bsd.launchdadd.plist',
'com.apple.cfprefsd.xpc.daemon.plist',
'com.apple.cmio.AppleCameraAssistant.plist',
'com.apple.cmio.AVCAssistant.plist',
'com.apple.cmio.IIDCVideoAssistant.plist',
'com.apple.cmio.VDCAssistant.plist',
'com.apple.comsat.plist',
'com.apple.configd.plist',
'com.apple.configureLocalKDC.plist',
'com.apple.CoreRAID.plist',
'com.apple.coreservices.appleevents.plist',
'com.apple.coreservices.appleid.passwordcheck.plist',
'com.apple.coreservices.launchservicesd.plist',
'com.apple.coreservicesd.plist',
'com.apple.corestorage.corestoraged.plist',
'com.apple.corestorage.corestoragehelperd.plist',
'com.apple.coresymbolicationd.plist',
'com.apple.cvmsServ.plist',
'com.apple.DiagnosticReportCleanUpDaemon.plist',
'com.apple.diskarbitrationd.plist',
'com.apple.diskmanagementd.plist',
'com.apple.displaypolicyd.plist',
'com.apple.distnoted.xpc.daemon.plist',
'com.apple.dnsextd.plist',
'com.apple.docsetinstalld.plist',
'com.apple.dpd.plist',
'com.apple.dspluginhelperd.plist',
'com.apple.DumpGPURestart.plist',
'com.apple.DumpPanic.plist',
'com.apple.dvdplayback.setregion.plist',
'com.apple.dynamic_pager.plist',
'com.apple.eapolcfg_auth.plist',
'com.apple.efax.plist',
'com.apple.efilogin-helper.plist',
'com.apple.emlog.plist',
'com.apple.emond.aslmanager.plist',
'com.apple.emond.plist',
'com.apple.eppc.plist',
'com.apple.familycontrols.plist',
'com.apple.FileCoordination.plist',
'com.apple.FileSyncAgent.sshd.plist',
'com.apple.findmymac.plist',
'com.apple.findmymacmessenger.plist',
'com.apple.firmwaresyncd.plist',
'com.apple.fontd.plist',
'com.apple.fontmover.plist',
'com.apple.FontWorker.plist',
'com.apple.fseventsd.plist',
'com.apple.ftp-proxy.plist',
'com.apple.getty.plist',
'com.apple.gkreport.plist',
'com.apple.gssd.plist',
'com.apple.hdiejectd.plist',
'com.apple.hidd.plist',
'com.apple.iCloudStats.plist',
'com.apple.iconservices.iconservicesd.plist',
'com.apple.IFCStart.plist',
'com.apple.installd.plist',
'com.apple.InternetSharing.plist',
'com.apple.IOAccelMemoryInfoCollector.plist',
'com.apple.IOBluetoothUSBDFU.plist',
'com.apple.kcproxy.plist',
'com.apple.kdumpd.plist',
'com.apple.Kerberos.digest-service.plist',
'com.apple.Kerberos.kadmind.plist',
'com.apple.Kerberos.kcm.plist',
'com.apple.Kerberos.kdc.plist',
'com.apple.Kerberos.kpasswdd.plist',
'com.apple.KernelEventAgent.plist',
'com.apple.kextd.plist',
'com.apple.kuncd.plist',
'com.apple.laterscheduler.plist',
'com.apple.locate.plist',
'com.apple.locationd.plist',
'com.apple.lockd.plist',
'com.apple.locum.plist',
'com.apple.logind.plist',
'com.apple.loginwindow.LFVTracer.plist',
'com.apple.loginwindow.plist',
'com.apple.loginwindow.secureerase.plist',
'com.apple.logkextloadsd.plist',
'com.apple.logsyswritesd.plist',
'com.apple.ManagedClient.cloudconfigurationd.plist',
'com.apple.ManagedClient.enroll.plist',
'com.apple.ManagedClient.plist',
'com.apple.ManagedClient.startup.plist',
'com.apple.mbicloudsetupd.plist',
'com.apple.mdmclient.daemon.plist',
'com.apple.mDNSResponder.plist',
'com.apple.mDNSResponderHelper.plist',
'com.apple.metadata.mds.index.plist',
'com.apple.metadata.mds.plist',
'com.apple.metadata.mds.scan.plist',
'com.apple.metadata.mds.spindump.plist',
'com.apple.msrpc.echosvc.plist',
'com.apple.msrpc.lsarpc.plist',
'com.apple.msrpc.mdssvc.plist',
'com.apple.msrpc.netlogon.plist',
'com.apple.msrpc.srvsvc.plist',
'com.apple.msrpc.wkssvc.plist',
'com.apple.mtmd.plist',
'com.apple.mtmfs.plist',
'com.apple.netauth.sys.auth.plist',
'com.apple.netauth.sys.gui.plist',
'com.apple.netbiosd.plist',
'com.apple.NetBootClientStatus.plist',
'com.apple.networkd.plist',
'com.apple.networkd_privileged.plist',
'com.apple.NetworkDiagnostics.plist',
'com.apple.NetworkLinkConditioner.plist',
'com.apple.newsyslog.plist',
'com.apple.nfsconf.plist',
'com.apple.nfsd.plist',
'com.apple.nis.ypbind.plist',
'com.apple.noticeboard.state.plist',
'com.apple.notifyd.plist',
'com.apple.ocspd.plist',
'com.apple.odproxyd.plist',
'com.apple.ODSAgent.plist',
'com.apple.opendirectoryd.plist',
'com.apple.pacemaker.plist',
'com.apple.PasswordService.plist',
'com.apple.PCIELaneConfigTool.plist',
'com.apple.periodic-daily.plist',
'com.apple.periodic-monthly.plist',
'com.apple.periodic-weekly.plist',
'com.apple.pfctl.plist',
'com.apple.pfd.plist',
'com.apple.platform.ptmd.plist',
'com.apple.postgres.plist',
'com.apple.powerd.plist',
'com.apple.powerd.swd.plist',
'com.apple.preferences.timezone.admintool.plist',
'com.apple.preferences.timezone.auto.plist',
'com.apple.printtool.daemon.plist',
'com.apple.racoon.plist',
'com.apple.RemoteDesktop.PrivilegeProxy.plist',
'com.apple.remotepairtool.plist',
'com.apple.ReportCrash.Root.plist',
'com.apple.ReportPanicService.plist',
'com.apple.revisiond.plist',
'com.apple.RFBEventHelper.plist',
'com.apple.rpcbind.plist',
'com.apple.rpmuxd.plist',
'com.apple.sandboxd.plist',
'com.apple.SCHelper.plist',
'com.apple.screensharing.plist',
'com.apple.scsid.plist',
'com.apple.security.agentMain.plist',
'com.apple.security.authhost.plist',
'com.apple.security.FDERecoveryAgent.plist',
'com.apple.security.syspolicy.plist',
'com.apple.securityd.plist',
'com.apple.securityd_service.plist',
'com.apple.ServerPerfLog.aslmanager.plist',
'com.apple.ServerPerfLog.plist',
'com.apple.sessionlogoutd.plist',
'com.apple.shutdown_monitor.plist',
'com.apple.sleepservicesd.plist',
'com.apple.smb.preferences.plist',
'com.apple.smbd.plist',
'com.apple.snhelper.plist',
'com.apple.softwareupdate_firstrun_tasks.plist',
'com.apple.softwareupdated.plist',
'com.apple.spindump.plist',
'com.apple.spindump_symbolicator.plist',
'com.apple.stackshot.plist',
'com.apple.statd.notify.plist',
'com.apple.storereceiptinstaller.plist',
'com.apple.SubmitDiagInfo.Root.plist',
'com.apple.suhelperd.plist',
'com.apple.syslogd.plist',
'com.apple.sysmond.plist',
'com.apple.systemkeychain.plist',
'com.apple.systempreferences.installer.plist',
'com.apple.SystemStarter.plist',
'com.apple.systemstats.analysis.plist',
'com.apple.systemstats.daily.plist',
'com.apple.systemstatsd.plist',
'com.apple.taskgated-helper.plist',
'com.apple.taskgated.plist',
'com.apple.tccd.system.plist',
'com.apple.TrustEvaluationAgent.system.plist',
'com.apple.ucupdate.plist',
'com.apple.uninstalld.plist',
'com.apple.unmountassistant.sysagent.plist',
'com.apple.usbd.plist',
'com.apple.usbmuxd.plist',
'com.apple.UserEventAgent-System.plist',
'com.apple.UserNotificationCenter.plist',
'com.apple.uucp.plist',
'com.apple.var-db-dslocal-backup.plist',
'com.apple.vsdbutil.plist',
'com.apple.warmd.plist',
'com.apple.wdhelper.plist',
'com.apple.webdavfs_load_kext.plist',
'com.apple.wifid.plist',
'com.apple.WindowServer.plist',
'com.apple.wwand.plist',
'com.apple.xpcd.plist',
'com.apple.xsan.plist',
'com.apple.xsanmgrd.plist',
'com.apple.xscertadmin.plist',
'com.apple.xscertd-helper.plist',
'com.apple.xscertd.plist']

_lSafeUserBin = ['2to3',
'2to3-',
'2to3-2.7',
'2to32.6',
'BuildStrings',
'CpMac',
'DeRez',
'GetFileInfo',
'MergePef',
'MvMac',
'RSA_SecurID_getpasswd',
'ResMerger',
'Rez',
'RezDet',
'RezWack',
'SetFile',
'SplitForks',
'UnRezWack',
'VBoxAutostart',
'VBoxBalloonCtrl',
'VBoxHeadless',
'VBoxManage',
'VBoxVRDP',
'VirtualBox',
'a2p',
'a2p5.12',
'a2p5.16',
'addftinfo',
'afconvert',
'afhash',
'afida',
'afinfo',
'afmtodit',
'afplay',
'agentxtrap',
'agvtool',
'alias',
'allmemory',
'applesingle',
'appletviewer',
'apply',
'apr-1-config',
'apropos',
'apt',
'apu-1-config',
'ar',
'arch',
'as',
'asa',
'asctl',
'at',
'atos',
'atq',
'atrm',
'atsutil',
'automator',
'auval',
'auvaltool',
'avconvert',
'avmetareadwrite',
'awk',
'banner',
'base64',
'basename',
'bashbug',
'batch',
'bc',
'bg',
'biff',
'binhex',
'bison',
'bitesize.d',
'bsdtar',
'bspatch',
'btmmdiagnose',
'bunzip2',
'bzcat',
'bzcmp',
'bzdiff',
'bzegrep',
'bzfgrep',
'bzgrep',
'bzip2',
'bzip2recover',
'bzless',
'bzmore',
'c++',
'c++filt',
'c2ph',
'c2ph5.12',
'c2ph5.16',
'c89',
'c99',
'c_rehash',
'caffeinate',
'cal',
'calendar',
'cancel',
'cap_mkdb',
'captoinfo',
'cc',
'cd',
'certtool',
'checknr',
'chflags',
'chfn',
'chgrp',
'chpass',
'chsh',
'cksum',
'clang',
'clang++',
'clear',
'cmp',
'cmpdylib',
'codesign',
'codesign_allocate',
'col',
'colcrt',
'colldef',
'colrm',
'column',
'comm',
'command',
'compress',
'config_data',
'config_data5.12',
'config_data5.16',
'corelist',
'corelist5.12',
'corelist5.16',
'cpan',
'cpan2dist',
'cpan2dist5.12',
'cpan2dist5.16',
'cpan5.12',
'cpan5.16',
'cpanp',
'cpanp-run-perl',
'cpanp-run-perl5.12',
'cpanp-run-perl5.16',
'cpanp5.12',
'cpanp5.16',
'cpio',
'cpp',
'cpu_profiler.d',
'cpuwalk.d',
'crc32',
'crc325.12',
'crc325.16',
'creatbyproc.d',
'crlrefresh',
'crontab',
'csplit',
'csreq',
'ctags',
'ctf_insert',
'cu',
'cups-config',
'cupstestdsc',
'cupstestppd',
'curl',
'curl-config',
'cut',
'cvaffinity',
'cvcp',
'cvmkdir',
'cvmkfile',
'dappprof',
'dapptrace',
'darwinup',
'db_archive',
'db_checkpoint',
'db_codegen',
'db_deadlock',
'db_dump',
'db_hotbackup',
'db_load',
'db_printlog',
'db_recover',
'db_stat',
'db_upgrade',
'db_verify',
'dbicadmin',
'dbicadmin5.12',
'dbicadmin5.16',
'dbilogstrip',
'dbilogstrip5.12',
'dbilogstrip5.16',
'dbiprof',
'dbiprof5.12',
'dbiprof5.16',
'dbiproxy',
'dbiproxy5.12',
'dbiproxy5.16',
'dc',
'defaults',
'desdp',
'diff',
'diff3',
'diffstat',
'dig',
'dirname',
'diskhits',
'dispqlen.d',
'ditto',
'dns-sd',
'dnsctl',
'dprofpp',
'dprofpp5.12',
'drutil',
'dscacheutil',
'dscl',
'dserr',
'dsexport',
'dsimport',
'dsmemberutil',
'dsymutil',
'dtruss',
'du',
'dwarfdump',
'easy_install',
'easy_install-2.5',
'easy_install-2.6',
'easy_install-2.7',
'efax',
'efix',
'egrep',
'emacs',
'emacs-undumped',
'emacsclient',
'enc2xs',
'enc2xs5.12',
'enc2xs5.16',
'encode_keychange',
'env',
'eqn',
'eqn2graph',
'erb',
'errinfo',
'etags',
'ex',
'execsnoop',
'expand',
'expect',
'extcheck',
'eyapp',
'eyapp5.12',
'eyapp5.16',
'false',
'fax',
'fc',
'fddist',
'fdesetup',
'fg',
'fgrep',
'file',
'filebyproc.d',
'filtercalltree',
'find',
'find2perl',
'find2perl5.12',
'find2perl5.16',
'findrule',
'findrule5.12',
'findrule5.16',
'finger',
'fixproc',
'flex',
'flex++',
'fmt',
'fold',
'fontrestore',
'footprint',
'formail',
'format-sql',
'format-sql5.12',
'format-sql5.16',
'from',
'fs_usage',
'ftp',
'funzip',
'fuser',
'fwkdp',
'fwkpfv',
'g++',
'gatherheaderdoc',
'gcc',
'gcov',
'gdiffmk',
'gem',
'gen_bridge_metadata',
'gencat',
'genstrings',
'getconf',
'getopt',
'getopts',
'git',
'git-cvsserver',
'git-receive-pack',
'git-shell',
'git-upload-archive',
'git-upload-pack',
'gm4',
'gnuattach',
'gnuclient',
'gnudoit',
'gnumake',
'gnuserv',
'gperf',
'grap2graph',
'grep',
'grn',
'grodvi',
'groff',
'groffer',
'grog',
'grolbp',
'grolj4',
'grops',
'grotty',
'groups',
'gunzip',
'gzcat',
'gzexe',
'gzip',
'h2ph',
'h2ph5.12',
'h2ph5.16',
'h2xs',
'h2xs5.12',
'h2xs5.16',
'hash',
'hdid',
'hdiutil',
'hdxml2manxml',
'head',
'headerdoc2html',
'heap',
'hexdump',
'hiutil',
'host',
'hostinfo',
'hotspot.d',
'hpftodit',
'htmltree',
'htmltree5.12',
'htmltree5.16',
'httpdstat.d',
'ibtool',
'iconutil',
'iconv',
'ictool',
'id',
'idle',
'idle2.5',
'idle2.6',
'idle2.7',
'idlj',
'imptrace',
'indent',
'indxbib',
'info',
'infocmp',
'infokey',
'infotocap',
'install',
'install-info',
'install_name_tool',
'instmodsh',
'instmodsh5.12',
'instmodsh5.16',
'instruments',
'iofile.d',
'iofileb.d',
'iopattern',
'iopending',
'iosnoop',
'iotop',
'ip2cc',
'ip2cc5.12',
'ip2cc5.16',
'ipcount',
'ipcount5.12',
'ipcount5.16',
'ipcrm',
'ipcs',
'ipmitool',
'ippfind',
'ipptool',
'iprofiler',
'iptab',
'iptab5.12',
'iptab5.16',
'irb',
'jar',
'jarsigner',
'java',
'javac',
'javadoc',
'javah',
'javap',
'javaws',
'jcmd',
'jconsole',
'jdb',
'jhat',
'jinfo',
'jmap',
'jobs',
'join',
'jot',
'jps',
'jrunscript',
'jsadebugd',
'json_pp',
'json_pp5.16',
'jstack',
'jstat',
'jstatd',
'jvisualvm',
'kcc',
'kdestroy',
'kextutil',
'keytool',
'kgetcred',
'kill.d',
'killall',
'kinit',
'klist',
'kpasswd',
'krb5-config',
'kswitch',
'lam',
'last',
'lastcomm',
'lastwords',
'latency',
'ld',
'ldapadd',
'ldapcompare',
'ldapdelete',
'ldapexop',
'ldapmodify',
'ldapmodrdn',
'ldappasswd',
'ldapsearch',
'ldapurl',
'ldapwhoami',
'leaks',
'leave',
'less',
'lessecho',
'lex',
'libnetcfg',
'libnetcfg5.12',
'libnetcfg5.16',
'libtool',
'lipo',
'lkbib',
'lldb',
'llvm-g++',
'llvm-gcc',
'loads.d',
'locale',
'localedef',
'locate',
'lockfile',
'logger',
'login',
'logname',
'look',
'lookbib',
'lorder',
'lp',
'lpoptions',
'lppasswd',
'lpq',
'lpr',
'lprm',
'lpstat',
'lsappinfo',
'lsbom',
'lsm',
'lsvfs',
'lwp-download',
'lwp-download5.12',
'lwp-download5.16',
'lwp-dump',
'lwp-dump5.12',
'lwp-dump5.16',
'lwp-mirror',
'lwp-mirror5.12',
'lwp-mirror5.16',
'lwp-request',
'lwp-request5.12',
'lwp-request5.16',
'm4',
'macbinary',
'macerror',
'macerror5.12',
'macerror5.16',
'machine',
'mail',
'mailq',
'mailstat',
'mailx',
'make',
'makeinfo',
'malloc_history',
'man',
'manpath',
'mcxquery',
'mcxrefresh',
'mddiagnose',
'mdfind',
'mdimport',
'mdimport32',
'mdls',
'mdutil',
'memcached',
'memory_pressure',
'mesg',
'mib2c',
'mib2c-update',
'mig',
'mkbom',
'mkdep',
'mkfifo',
'mklocale',
'mktemp',
'mmroff',
'mnthome',
'moose-outdated',
'moose-outdated5.12',
'moose-outdated5.16',
'more',
'mp2bug',
'msgs',
'nano',
'nasm',
'native2ascii',
'nbdst',
'nc',
'ncal',
'ncdestroy',
'ncurses5.4-config',
'ndisasm',
'neqn',
'net-server',
'net-server5.16',
'net-snmp-cert',
'net-snmp-config',
'net-snmp-create-v3-user',
'nettop',
'newaliases',
'newgrp',
'newproc.d',
'nfsstat',
'nice',
'nl',
'nm',
'nmedit',
'nohup',
'notifyutil',
'nroff',
'nslookup',
'nsupdate',
'ntp-keygen',
'ntpq',
'od',
'odutil',
'open',
'opendiff',
'opensnoop',
'openssl',
'orbd',
'osacompile',
'osadecompile',
'osalang',
'osascript',
'otool',
'pack200',
'package-stash-conflicts',
'package-stash-conflicts5.12',
'package-stash-conflicts5.16',
'pagesize',
'pagestuff',
'par.pl',
'par5.12.pl',
'par5.16.pl',
'parl',
'parl5.12',
'parl5.16',
'parldyn',
'parldyn5.12',
'parldyn5.16',
'passwd',
'paste',
'patch',
'pathchk',
'pathopens.d',
'pbcopy',
'pbpaste',
'pcap-config',
'pcsctest',
'pcsctool',
'pdfroff',
'perfdiagnose',
'perl',
'perl5.12',
'perl5.16',
'perlbug',
'perlbug5.12',
'perlbug5.16',
'perldoc',
'perldoc5.12',
'perldoc5.16',
'perlivp',
'perlivp5.12',
'perlivp5.16',
'perlthanks',
'perlthanks5.12',
'perlthanks5.16',
'pfbtops',
'pgrep',
'phar',
'phar.phar',
'php',
'php-config',
'phpize',
'pic',
'pic2graph',
'pico',
'piconv',
'piconv5.12',
'piconv5.16',
'pidpersec.d',
'pkgbuild',
'pkill',
'pl',
'pl2pm',
'pl2pm5.12',
'pl2pm5.16',
'plockstat',
'pluginkit',
'plutil',
'pmset',
'pod2html',
'pod2html5.12',
'pod2html5.16',
'pod2latex',
'pod2latex5.12',
'pod2latex5.16',
'pod2man',
'pod2man5.12',
'pod2man5.16',
'pod2readme',
'pod2readme5.12',
'pod2readme5.16',
'pod2text',
'pod2text5.12',
'pod2text5.16',
'pod2usage',
'pod2usage5.12',
'pod2usage5.16',
'podchecker',
'podchecker5.12',
'podchecker5.16',
'podselect',
'podselect5.12',
'podselect5.16',
'policytool',
'post-grohtml',
'power_report.sh',
'powermetrics',
'pp',
'pp5.12',
'pp5.16',
'ppdc',
'ppdhtml',
'ppdi',
'ppdmerge',
'ppdpo',
'pr',
'pre-grohtml',
'priclass.d',
'pridist.d',
'printenv',
'printf',
'procmail',
'procsystime',
'productbuild',
'productsign',
'profiles',
'prove',
'prove5.12',
'prove5.16',
'psed',
'psed5.12',
'psed5.16',
'pstopdf',
'pstruct',
'pstruct5.12',
'pstruct5.16',
'ptar',
'ptar5.12',
'ptar5.16',
'ptardiff',
'ptardiff5.12',
'ptardiff5.16',
'ptargrep',
'ptargrep5.16',
'pubsub',
'pwhich',
'pwhich5.16',
'pwpolicy',
'pydoc',
'pydoc2.5',
'pydoc2.6',
'pydoc2.7',
'python',
'python-config',
'python2.5',
'python2.5-config',
'python2.6',
'python2.6-config',
'python2.7',
'python2.7-config',
'pythonw',
'pythonw2.5',
'pythonw2.6',
'pythonw2.7',
'qc2movie',
'qlmanage',
'qtdefaults',
'quota',
'rails',
'rake',
'ranlib',
'rdoc',
'read',
'readlink',
'rebase',
'redo_prebinding',
'refer',
'renice',
'reset',
'resolveLinks',
'rev',
'ri',
'rlogin',
'rmic',
'rmid',
'rmiregistry',
'rpcgen',
'rs',
'rsh',
'rsync',
'ruby',
'runocc.d',
'ruptime',
'rvictl',
'rview',
'rvim',
'rwbypid.d',
'rwbytype.d',
'rwho',
'rwsnoop',
's2p',
's2p5.12',
's2p5.16',
'sample',
'sampleproc',
'sandbox-exec',
'sandbox-simplify',
'sar',
'say',
'sc_usage',
'scandeps.pl',
'scandeps5.12.pl',
'scandeps5.16.pl',
'schemagen',
'scp',
'screen',
'script',
'sdef',
'sdiff',
'sdp',
'sdx',
'security',
'sed',
'seeksize.d',
'segedit',
'seq',
'serialver',
'servertool',
'setregion',
'setuids.d',
'sftp',
'shar',
'shasum',
'shasum5.12',
'shasum5.16',
'shlock',
'showmount',
'sigdist.d',
'sips',
'size',
'slogin',
'smbutil',
'smtpd.py',
'smtpd2.5.py',
'smtpd2.6.py',
'smtpd2.7.py',
'snfsdefrag',
'snmp-bridge-mib',
'snmpbulkget',
'snmpbulkwalk',
'snmpconf',
'snmpdelta',
'snmpdf',
'snmpget',
'snmpgetnext',
'snmpinform',
'snmpnetstat',
'snmpset',
'snmpstatus',
'snmptable',
'snmptest',
'snmptranslate',
'snmptrap',
'snmpusm',
'snmpvacm',
'snmpwalk',
'sntp',
'soelim',
'sort',
'spfd',
'spfd5.12',
'spfd5.16',
'spfquery',
'spfquery5.12',
'spfquery5.16',
'splain',
'splain5.12',
'splain5.16',
'split',
'sqlite3',
'srm',
'ssh',
'ssh-add',
'ssh-agent',
'ssh-keygen',
'ssh-keyscan',
'stat',
'stringdups',
'strings',
'strip',
'stty.pl',
'stty5.12.pl',
'stty5.16.pl',
'su',
'sudo',
'sum',
'svn',
'svnadmin',
'svndumpfilter',
'svnlook',
'svnserve',
'svnsync',
'svnversion',
'sw_vers',
'symbols',
'symbolscache',
'syscallbypid.d',
'syscallbyproc.d',
'syscallbysysc.d',
'sysdiagnose',
'syslog',
'tab2space',
'tabs',
'tail',
'talk',
'tar',
'tbl',
'tccutil',
'tclsh',
'tclsh8.4',
'tclsh8.5',
'tee',
'telnet',
'testrb',
'texi2dvi',
'texi2pdf',
'texindex',
'textutil',
'tfmtodit',
'tftp',
'tic',
'tidy',
'tiff2icns',
'tiffutil',
'time',
'timer_analyser.d',
'timerfires',
'tkcon',
'tkmib',
'tkpp',
'tkpp5.12',
'tkpp5.16',
'tmdiagnose',
'tmutil',
'tnameserv',
'toe',
'top',
'tops',
'topsyscall',
'topsysproc',
'touch',
'tput',
'tr',
'trace',
'traptoemail',
'treereg',
'treereg5.12',
'treereg5.16',
'trial',
'troff',
'true',
'tset',
'tsort',
'tty',
'twistd',
'type',
'ubcontrol',
'ul',
'ulimit',
'umask',
'unalias',
'uname',
'uncompress',
'unexpand',
'unifdef',
'unifdefall',
'uniq',
'units',
'unpack200',
'unvis',
'unzip',
'unzipsfx',
'update_dyld_shared_cache',
'uptime',
'users',
'uucp',
'uudecode',
'uuencode',
'uuidgen',
'uulog',
'uuname',
'uupick',
'uustat',
'uuto',
'uux',
'vboxwebsrv',
'vi',
'view',
'vim',
'vimdiff',
'vimtutor',
'vis',
'vm_stat',
'vmmap',
'w',
'wait',
'wall',
'wc',
'wdutil',
'weblatency.d',
'what',
'whatis',
'whereis',
'which',
'who',
'whoami',
'whois',
'wish',
'wish8.4',
'wish8.5',
'write',
'wsgen',
'wsimport',
'xar',
'xargs',
'xattr',
'xattr-2.5',
'xattr-2.6',
'xattr-2.7',
'xcode-select',
'xcodebuild',
'xcrun',
'xed',
'xgettext.pl',
'xgettext5.12.pl',
'xgettext5.16.pl',
'xip',
'xjc',
'xml2-config',
'xml2man',
'xmlcatalog',
'xmllint',
'xpath',
'xpath5.12',
'xpath5.16',
'xslt-config',
'xsltproc',
'xsubpp',
'xsubpp5.12',
'xsubpp5.16',
'xxd',
'yacc',
'yes',
'ypcat',
'ypmatch',
'ypwhich',
'zcat',
'zcmp',
'zdiff',
'zegrep',
'zfgrep',
'zforce',
'zgrep',
'zip',
'zipcloak',
'zipdetails',
'zipdetails5.16',
'zipgrep',
'zipinfo',
'zipnote',
'zipsplit',
'zless',
'zmore',
'znew',
'zprint']

_lSafeUsersShared = ['.localized',
'Library',
'SC Info']

def darwin():
  if not 'Darwin' in _sCurrentOS:
    print 'ERROR - MacOSX Only...' # Oh boy !
    exit(1)

def init():
  print '>>> Zeds '   + _sCurrentVersion + ' -- ' + _sCurrentYear + ' <<<'
  print '>>> Author : ' + _sAuthor + '\n'

  print '    User : ' + _sCurrentUser
  print '    Time : ' + _sCurrentTime 
  print '      OS : ' + _sCurrentOS
  print ''

def update():
  bFound = False
  pProc = subprocess.Popen(['softwareupdate','-l'],
  	stdin = subprocess.PIPE,
  	stdout = subprocess.PIPE,
  	stderr = subprocess.PIPE
  	)
  (out, err) = pProc.communicate()
  sIsUpToDate =  out + err
  if "No new software available" in sIsUpToDate:
    bFound = True
  if bFound == False:
    print 'U0 - Update(s) Available(s)' 

def hosts():
  with open('/etc/hosts','r') as fHosts:
    for sLine in fHosts:
      bWhiteList = False
      sArgs = sLine.strip();
      sArgs = sArgs.replace(' ','')
      sArgs = sArgs.replace('	','')
      for sRules in _lSafeHosts:
        if sRules in sArgs:
          bWhiteList = True
      if bWhiteList == False:
        print 'N0 - HOSTS: ' + sLine


def startup_item():
  for f in os.listdir('/Library/StartupItems/'):
    print 'R0 - [/Library/StartupItems] ' + f

def agents():
  # Administrator Agents
  for f in os.listdir('/Library/LaunchAgents/'):
    print 'A0 - [/Library/LaunchAgents] ' + f
    
  # User Agents
  for f in os.listdir("/Users/" + _sCurrentUser + "/Library/LaunchAgents/"):
    print 'L0 - [~/Library/LaunchAgents] ' + f

  # System Agents  
  for f in os.listdir('/System/Library/LaunchAgents/'):
    bFound = False
    for sWhiteList in _lSafeSystemAgents:
      if sWhiteList in f:
        bFound = True	
    if bFound == False:
      print 'L0 - [/System/Library/LaunchAgents] ' + f

def daemons():
  # Administrator Deamons
  for f in os.listdir('/Library/LaunchDaemons/'):
    print 'L1 - [/Library/LaunchDaemons] ' + f

  # System Agents  
  for f in os.listdir('/System/Library/LaunchDaemons/'):
    bFound = False
    for sWhiteList in _lSafeSystemDaemons:
      if sWhiteList in f:
        bFound = True	
    if bFound == False:
      print 'L1 - [/System/Library/LaunchDaemons] ' + f

def apps():
  for f in os.listdir("/Applications/"):
    if not '.DS_Store' in f and not '.localized' in f:
      if 'MacD' in f or 'MacPr' in f or 'Mac D' in f or 'MacSw' in f or 'Mac P' in f:
        print 'A1 - [Applications] ' + f + ' <- SUSPICIOUS'
      else:
        print 'A0 - [Applications] ' + f

def bin():
  for f in os.listdir("/usr/bin/"):
    bFound = False
    for sWhiteList in _lSafeUserBin:
      if sWhiteList == f:
        bFound = True
    if bFound == False:
      print 'B0 - [/usr/bin] ' + f

  for f in os.listdir("/usr/local/bin"):
    print 'B1 - [/usr/local/bin] ' + f  

def shared():
  for f in os.listdir("/Users/Shared/"):
    bFound = False
    for sWhiteList in _lSafeUsersShared:
      if sWhiteList in f:
        bFound = True	
    if bFound == False:
      print 'O1 - [/Users/Shared/] ' + f 

def safari_start():
  f = biplist.readPlist("/Users/" + _sCurrentUser + "/Library/Preferences/com.apple.Safari.plist")
  print 'S0 - [LastOSVersionSafariWasLaunchedOn] ' + f["LastOSVersionSafariWasLaunchedOn"]
  print 'S0 - [NewestLaunchedSafariVersion] ' + f["NewestLaunchedSafariVersion"]
  print 'S0 - [HomePage] ' + f["HomePage"]

def safari_plugins():
  for f in os.listdir("/Library/Internet Plug-Ins/"):
    print 'S1 - [/Library/Internet Plug-Ins] ' + f

  for f in os.listdir("/Users/" + _sCurrentUser + "/Library/Safari/Extensions/"):
    if not 'Extensions.plist' in f:
      print 'S2 - [~/Library/Safari/Extensions/] ' + f

def main():
  init()
  darwin()
  # update()
  print '-----------------------------------------------------------------------'
  agents()
  print '-----------------------------------------------------------------------'
  daemons()
  print '-----------------------------------------------------------------------'
  apps()
  print '-----------------------------------------------------------------------'
  bin()
  print '-----------------------------------------------------------------------'
  shared()
  print '-----------------------------------------------------------------------'
  safari_start()
  safari_plugins()


if __name__ == "__main__":
  main()